### PR TITLE
Fix for unicode not showing up correctly from xkcd

### PR DESCRIPTION
**Pull request by eyezis**
honestly i have no idea if it even works but it should

### CODE REVIEW

**Comment by JuanPotato** [comment]
lol

**Comment by TiagoDanin** [comment]
Where can i get the lib?

**Comment by eyezis** [comment]
`luarocks install luautf8`

**Comment by TiagoDanin** [comment]
- Very good lol
- [Note] Missing import lib in utilities.lua:

`Error: ./otouto/utilities.lua:319: attempt to index global 'utf8' (a nil value)`

**Comment by eyezis** [comment]
I put the require in the wrong place.

**Comment by eyezis** [comment]
@topkecleon I have no idea what im doing. Could you close this one and use the new one?

**Pull request closed without merging**
