### PR TITLE
Improvements and fix

### PR DESCRIPTION
**Pull request by TiagoDanin**
FIX: 
help of bandersnatch

Improvements: [New design](https://github.com/topkecleon/otouto/#style)
image

### CODE REVIEW

**Comment by topkecleon** [comment]
The bandersnatch changes are iffy (creates global var "output" as only the now-defunct "message" is localized), and to be honest, I'm not sure about the monospacing for that.
Otherwise, I like the changes. Change for translate.lua should also be applied to remind.lua and echo.lua (for when it echos in supergroups).
Mind throwing that in so we can do this all in one fell swoop?

**Comment by TiagoDanin** [comment]
Yep, ...
Missing a standard for sending of messages
What do you think of removes the SendReply to plugins?

**Comment by topkecleon** [comment]
Because bandersnatch's output is frivolous, I would probably italicize it.
I'm not sure what you mean, though. sendReply is a nice shortcut. Maybe a second method would be good to include markdown support (or add an optional arg to sendReply to enable it).

**Comment by TiagoDanin** [comment]
- Monospace is applied in text with more of 3 line
- FIX  libreme conflict with database (lastfm)

**Comment by TiagoDanin** [comment]
Note: still not ready for merge

**Comment by TiagoDanin** [comment]
Ready:
- FIX gImages

**Pull request closed without merging**
